###

GET http://citilink-product.herokuapp.com/products

###

POST http://citilink-product.herokuapp.com/products/caps
Content-Type: application/json

{
  "id": 0,
  "name": "Red Cap",
  "price": 500,
  "color": "red",
  "size": "M"
}

###

POST http://citilink-product.herokuapp.com/products/books
Content-Type: application/json

{
  "id": 0,
  "name": "Anna Karenina",
  "price": 900,
  "author": "Tolstoy"
}

###

POST http://citilink-product.herokuapp.com/products/laptops
Content-Type: application/json

{
  "id": 0,
  "name": "Lenovo",
  "price": 33900,
  "screenDiagonal": 14,
  "randomAccessMemory": 4,
  "processor": "Intel Core "
}

###

POST http://citilink-product.herokuapp.com/products/smartphones
Content-Type: application/json

{
  "id": 0,
  "name": "Apple iPhone 12",
  "price": 78000,
  "display": 6.1,
  "memory": 128
}

###

GET http://citilink-product.herokuapp.com/products/search?text=anna

###

GET http://citilink-product.herokuapp.com/products/search?text=tolstoy

###

GET http://citilink-product.herokuapp.com/products/search?text=Intel


###

GET http://citilink-product.herokuapp.com/products/catalog/books

###

GET http://citilink-product.herokuapp.com/products/catalog/caps

###

GET http://citilink-product.herokuapp.com/products/catalog/laptops

###

GET http://citilink-product.herokuapp.com/products/catalog/smartphones


###

PUT http://citilink-product.herokuapp.com/products/2
Content-Type: application/json

{
  "name": "black cap",
  "price": 1000
}

###

PUT http://citilink-product.herokuapp.com/products/4
Content-Type: application/json

{
  "name": "Apple IPhone 11",
  "price": 65000
}

###

DELETE http://citilink-product.herokuapp.com/products/1













